services:
  rabbitmq:
    image: "rabbitmq:3.10.7-management-alpine"
    ports:
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - aggregator
      
  postgres:
    image: "postgres:14.4-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    networks:
      - aggregator
networks:
  aggregator:
